#!/usr/bin/env node
import http from "node:http";

const port = Number.parseInt(process.env.MOCK_JUDGE_PORT ?? "8123", 10);
const host = process.env.MOCK_JUDGE_HOST ?? "127.0.0.1";
const severity = process.env.MOCK_JUDGE_SEVERITY ?? "critical";
const verdict = process.env.MOCK_JUDGE_VERDICT ?? (severity === "low" ? "warn" : "fail");
const shouldBlock = parseBoolean(process.env.MOCK_JUDGE_SHOULD_BLOCK, severity === "critical" || severity === "high");

const response = {
  verdict,
  should_block: shouldBlock,
  confidence: 0.95,
  scores: {
    user_intent: 3,
    correctness: severity === "critical" ? 2 : 4,
    completeness: 3,
    safety_security: 4,
    maintainability: 4,
    evidence: 4
  },
  summary: `Mock judge returned a ${severity} issue.`,
  issues: [
    {
      severity,
      category: "correctness",
      message: "Mock judge issue",
      evidence: "This response was generated by scripts/mockJudge.mjs.",
      suggested_fix: "Use this mock to verify agy-judge policy and output behavior."
    }
  ],
  required_changes: severity === "critical" ? ["Address the mocked critical issue."] : [],
  optional_improvements: severity === "critical" ? [] : ["Review the mocked non-critical issue."],
  judge_notes: "Development-only mock judge response."
};

const server = http.createServer((req, res) => {
  if (req.url === "/v1/chat/completions" && req.method === "POST") {
    req.resume();
    res.writeHead(200, { "content-type": "application/json" });
    res.end(
      JSON.stringify({
        choices: [{ message: { content: JSON.stringify(response) } }]
      })
    );
    return;
  }

  if (req.url === "/health") {
    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify({ ok: true }));
    return;
  }

  res.writeHead(404, { "content-type": "application/json" });
  res.end(JSON.stringify({ error: "not found" }));
});

server.on("error", (error) => {
  console.error(`mock judge failed to listen on ${host}:${port}: ${error.message}`);
  process.exitCode = 1;
});

server.listen(port, host, () => {
  console.log(`mock judge listening on http://${host}:${port}/v1`);
  console.log(`severity=${severity} verdict=${verdict} should_block=${shouldBlock}`);
});

function parseBoolean(value, fallback) {
  if (value === undefined) return fallback;
  return /^(1|true|yes|on)$/i.test(value);
}
